# Generated by Django 4.1.3 on 2022-11-25 18:14

from django.conf import settings
from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_date', models.DateField()),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid', models.BooleanField(default=False)),
                ('provider_social_reason', models.TextField(max_length=100)),
                ('provider_cnpj', models.TextField(max_length=25)),
                ('provider', models.ForeignKey(on_delete=models.SET(payments.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
