# Generated by Django 4.1.3 on 2022-11-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
    ]
