# Generated by Django 4.1.3 on 2022-11-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_cnpj',
            field=models.TextField(default=5198749848, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_social_reason',
            field=models.TextField(default='SocielReason', max_length=100),
            preserve_default=False,
        ),
    ]
