# Generated by Django 4.1.3 on 2022-11-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_provider_cnpj_payment_provider_social_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='emission_date',
            field=models.DateField(),
        ),
    ]
