# Generated by Django 4.1.3 on 2022-11-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticipate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('old_due_date', models.DateField()),
                ('new_due_date', models.DateField()),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.TextField(choices=[('not_reviewed', 'Not Reviewed'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='not_reviewed', max_length=20)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payment')),
            ],
        ),
    ]
