# Generated by Django 4.1.3 on 2022-11-27 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_anticipate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='old_due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
