# Generated by Django 4.1.3 on 2022-11-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_old_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='original_value',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
